// ignore_for_file: prefer_const_constructors, deprecated_member_use

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  final _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      dialogBackgroundColor: appTheme.dark3Color,
      useMaterial3: true,
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.onPrimaryContainer.withOpacity(1),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(
              14,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: colorScheme.primary,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(
              16,
            ),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: colorScheme.primaryContainer,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'SF Pro Display',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            13,
          ),
          fontFamily: 'Uniform Pro Extra Condensed',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            12,
          ),
          fontFamily: 'SF Pro Display',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            40,
          ),
          fontFamily: 'Uniform Pro Extra Condensed',
          fontWeight: FontWeight.w400,
        ),
        headlineMedium: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            28,
          ),
          fontFamily: 'Uniform Pro Extra Condensed',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: colorScheme.onPrimaryContainer.withOpacity(1),
          fontSize: getFontSize(
            22,
          ),
          fontFamily: 'Uniform Pro Extra Condensed',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: colorScheme.primary,
          fontSize: getFontSize(
            16,
          ),
          fontFamily: 'SF Pro Display',
          fontWeight: FontWeight.w700,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFFBBF246),
    primaryContainer: Color(0XFF384046),
    secondary: Color(0XFF384046),
    secondaryContainer: Color(0XFFD9D9D9),
    tertiary: Color(0XFF384046),
    tertiaryContainer: Color(0XFFD9D9D9),

    // Background colors
    background: Color(0XFF384046),

    // Surface colors
    surface: Color(0XFF384046),
    surfaceTint: Color(0XFF242C31),
    surfaceVariant: Color(0XFFD9D9D9),

    // Error colors
    error: Color(0XFF242C31),
    errorContainer: Color(0XFF34C057),
    onError: Color(0XFFEAEAEA),
    onErrorContainer: Color(0XFF192126),

    // On colors(text colors)
    onBackground: Color(0X75FFFFFF),
    onInverseSurface: Color(0XFFEAEAEA),
    onPrimary: Color(0XFF242C31),
    onPrimaryContainer: Color(0X75FFFFFF),
    onSecondary: Color(0X75FFFFFF),
    onSecondaryContainer: Color(0XFF242C31),
    onTertiary: Color(0X75FFFFFF),
    onTertiaryContainer: Color(0XFF242C31),

    // Other colors
    outline: Color(0XFF242C31),
    outlineVariant: Color(0XFF384046),
    scrim: Color(0XFF384046),
    shadow: Color(0XFF242C31),

    // Inverse colors
    inversePrimary: Color(0XFF384046),
    inverseSurface: Color(0XFF242C31),

    // Pending colors
    onSurface: Color(0X75FFFFFF),
    onSurfaceVariant: Color(0XFF242C31),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  Color get buttonColor => Color(0XFFBBF246);
  Color get whiteColor => Color(0XFFFFFFFF);
  Color get dark3Color => Color(0XFF252D32);
  Color get dark1Color => Color(0XFF192126);

  // BlueGray
  Color get blueGray300 => Color(0XFFA3A3B5);
  Color get blueGray400 => Color(0XFF888888);
  Color get fillBlack => Color(0XFF30373B);

  // Gray
  Color get gray600 => Color(0XFF808080);
  Color get gray700 => Color(0XFF666666);

  // Green
  Color get green500 => Color(0XFF34C759);
  Color get greenA700 => Color(0XFF04B155);

  // Indigo
  Color get indigo400 => Color(0XFF5856D6);
  Color get indigo800 => Color(0XFF263B80);

  // Orange
  Color get orangeA200 => Color(0XFFEFA83C);

  // Pink
  Color get pink400 => Color(0XFFD6567C);

  // Purple
  Color get purple400 => Color(0XFF9D56D6);

  // Red
  Color get red400 => Color(0XFFD65656);
  Color get red700 => Color(0XFFCD3232);

  // Yellow
  Color get yellowA700 => Color(0XFFFDCF00);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
closeApp() {
  Future.delayed(const Duration(milliseconds: 1000), () {
    SystemNavigator.pop();
  });
}
// ignore: non_constant_identifier_names
Widget animation_function(index, child,
    {Duration? listAnimation, Duration? slideduration, Duration? slidedelay}) {
  return AnimationConfiguration.staggeredList(
    position: index,
    duration: listAnimation ?? Duration(milliseconds: 375),
    child: SlideAnimation(
      duration: slideduration ?? Duration(milliseconds: 50),
      delay: slidedelay ?? Duration(milliseconds: 50),
      child: FadeInAnimation(
        child: child,
      ),
    ),
  );
}
