// ignore_for_file: prefer_const_constructors, deprecated_member_use

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  final _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  final Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  final Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      dialogBackgroundColor: appTheme.dark3Color,
      useMaterial3: true,
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      fontFamily: GoogleFonts.urbanist().fontFamily,
      textTheme: TextThemes.textTheme(colorScheme),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.onPrimaryContainer.withOpacity(1),
          textStyle: GoogleFonts.urbanist(
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          minimumSize: Size.fromHeight(56),
          padding: EdgeInsets.symmetric(vertical: 16, horizontal: 24),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Color(0XFFFFFFFF),
          shape: RoundedRectangleBorder(
            side: BorderSide(
              color: colorScheme.primary,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(12),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: colorScheme.primaryContainer,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => GoogleFonts.urbanistTextTheme(
    TextTheme(
      displayLarge: GoogleFonts.urbanist(
        fontSize: 32,
        fontWeight: FontWeight.bold,
        color: Colors.white,
      ),
      displayMedium: GoogleFonts.urbanist(
        fontSize: 28,
        fontWeight: FontWeight.bold,
        color: Colors.white,
      ),
      titleLarge: GoogleFonts.urbanist(
        fontSize: 24,
        fontWeight: FontWeight.w600,
        color: Colors.white,
      ),
      titleMedium: GoogleFonts.urbanist(
        fontSize: 18,
        fontWeight: FontWeight.w600,
        color: Colors.white,
      ),
      bodyLarge: GoogleFonts.urbanist(
        fontSize: 16,
        fontWeight: FontWeight.normal,
        color: colorScheme.onPrimaryContainer.withOpacity(1),
      ),
      bodyMedium: GoogleFonts.urbanist(
        fontSize: 14,
        fontWeight: FontWeight.normal,
        color: colorScheme.onPrimaryContainer.withOpacity(1),
      ),
      bodySmall: GoogleFonts.urbanist(
        fontSize: 12,
        fontWeight: FontWeight.normal,
        color: colorScheme.onPrimaryContainer.withOpacity(1),
      ),
      labelLarge: GoogleFonts.urbanist(
        fontSize: 16,
        fontWeight: FontWeight.bold,
        color: Colors.black,
      ),
      headlineMedium: GoogleFonts.urbanist(
        fontSize: 28,
        fontWeight: FontWeight.w400,
        color: colorScheme.onPrimaryContainer.withOpacity(1),
      ),
    ),
  );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    primary: Color(0XFFCDFF4D),
    primaryContainer: Color(0XFF384046),
    secondary: Color(0XFF384046),
    secondaryContainer: Color(0XFFD9D9D9),
    tertiary: Color(0XFF384046),
    tertiaryContainer: Color(0XFFD9D9D9),

    background: Color(0XFF192126),

    surface: Color(0XFF252D32),
    surfaceTint: Color(0XFF242C31),
    surfaceVariant: Color(0XFFD9D9D9),

    error: Color(0XFF242C31),
    errorContainer: Color(0XFF34C057),
    onError: Color(0XFFEAEAEA),
    onErrorContainer: Color(0XFF192126),

    onBackground: Color(0X75FFFFFF),
    onInverseSurface: Color(0XFFEAEAEA),
    onPrimary: Color(0XFF000000),
    onPrimaryContainer: Color(0XFFFFFFFF),
    onSecondary: Color(0X75FFFFFF),
    onSecondaryContainer: Color(0XFF242C31),
    onTertiary: Color(0X75FFFFFF),
    onTertiaryContainer: Color(0XFF242C31),

    outline: Color(0XFF242C31),
    outlineVariant: Color(0XFF384046),
    scrim: Color(0XFF384046),
    shadow: Color(0XFF242C31),

    inversePrimary: Color(0XFF384046),
    inverseSurface: Color(0XFF242C31),

    onSurface: Color(0XFFFFFFFF),
    onSurfaceVariant: Color(0XFF242C31),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  Color get buttonColor => Color(0XFFCDFF4D);
  Color get whiteColor => Color(0XFFFFFFFF);
  Color get dark3Color => Color(0XFF252D32);
  Color get dark1Color => Color(0XFF192126);

  // BlueGray
  Color get blueGray300 => Color(0XFFA3A3B5);
  Color get blueGray400 => Color(0XFF888888);
  Color get fillBlack => Color(0XFF30373B);

  // Gray
  Color get gray600 => Color(0XFF808080);
  Color get gray700 => Color(0XFF666666);

  // Green
  Color get green500 => Color(0XFF34C759);
  Color get greenA700 => Color(0XFF04B155);

  // Indigo
  Color get indigo400 => Color(0XFF5856D6);
  Color get indigo800 => Color(0XFF263B80);

  // Orange
  Color get orangeA200 => Color(0XFFEFA83C);

  // Pink
  Color get pink400 => Color(0XFFD6567C);

  // Purple
  Color get purple400 => Color(0XFF9D56D6);

  // Red
  Color get red400 => Color(0XFFD65656);
  Color get red700 => Color(0XFFCD3232);

  // Yellow
  Color get yellowA700 => Color(0XFFFDCF00);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
closeApp() {
  Future.delayed(const Duration(milliseconds: 1000), () {
    SystemNavigator.pop();
  });
}
// ignore: non_constant_identifier_names
Widget animation_function(index, child,
    {Duration? listAnimation, Duration? slideduration, Duration? slidedelay}) {
  return AnimationConfiguration.staggeredList(
    position: index,
    duration: listAnimation ?? Duration(milliseconds: 375),
    child: SlideAnimation(
      duration: slideduration ?? Duration(milliseconds: 50),
      delay: slidedelay ?? Duration(milliseconds: 50),
      child: FadeInAnimation(
        child: child,
      ),
    ),
  );
}
